#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-krb5
Version  : 0.3.0
Release  : 3
URL      : https://files.pythonhosted.org/packages/d4/4e/a18208fb107ada38738627b116a5fe55af96934957006ae26642584d69b2/krb5-0.3.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/d4/4e/a18208fb107ada38738627b116a5fe55af96934957006ae26642584d69b2/krb5-0.3.0.tar.gz
Summary  : Kerberos API bindings for Python
Group    : Development/Tools
License  : MIT
Requires: pypi-krb5-license = %{version}-%{release}
Requires: pypi-krb5-python = %{version}-%{release}
Requires: pypi-krb5-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : e2fsprogs-dev
BuildRequires : krb5-dev
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)

%description
# Python Kerberos 5 Library
[![Test workflow](https://github.com/jborean93/pykrb5/actions/workflows/ci.yml/badge.svg)](https://github.com/jborean93/pykrb5/actions/workflows/ci.yml)
[![PyPI version](https://badge.fury.io/py/krb5.svg)](https://badge.fury.io/py/krb5)
[![License](https://img.shields.io/badge/license-MIT-blue.svg)](https://github.com/jborean93/pykrb5/blob/main/LICENSE)

%package license
Summary: license components for the pypi-krb5 package.
Group: Default

%description license
license components for the pypi-krb5 package.


%package python
Summary: python components for the pypi-krb5 package.
Group: Default
Requires: pypi-krb5-python3 = %{version}-%{release}

%description python
python components for the pypi-krb5 package.


%package python3
Summary: python3 components for the pypi-krb5 package.
Group: Default
Requires: python3-core
Provides: pypi(krb5)

%description python3
python3 components for the pypi-krb5 package.


%prep
%setup -q -n krb5-0.3.0
cd %{_builddir}/krb5-0.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1649777957
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-krb5
cp %{_builddir}/krb5-0.3.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-krb5/8a44655c77dbb71243a0df4c3acc932bdd73e4fb
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-krb5/8a44655c77dbb71243a0df4c3acc932bdd73e4fb

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
